sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: myjavastudy0306
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wxc0667fca6a16d120
    secret: 6d700cb744f2a9b3e262698fa4f761ac
  shop:
    address: 江西省南昌市青山湖区上海北路
  baidu:
    ak: CB3flrn6z4iaXhTZ8gS9JVDKIjhqpuKC
